extern int    CFG_0[5];
extern int    CFG_1;
extern float  CFG_2[2];
extern float  CFG_3;
extern double CFG_4[2];
extern double CFG_5;
extern char   CFG_6[16];
extern bool   CFG_7;
extern bool   CFG_8[3];
